on:
  push:
    branches: master

name: pkgdown

jobs:
  pkgdown:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master
      - name: Install dependencies
        run: |
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE)
          remotes::install_dev("pkgdown")
          remotes::install_github("tidyverse/tidytemplate")
        shell: Rscript {0}
      - name: Install package
        run: R CMD INSTALL .
      - name: Install spacy
        run: |
          Rscript -e "reticulate::install_miniconda()"
          echo "options(reticulate.conda_binary = reticulate:::miniconda_conda())" >> .Rprofile
          Rscript -e "reticulate::conda_create('r-reticulate', packages = 'python==3.6.9')"
          Rscript -e "spacyr::spacy_install(prompt = FALSE)"
      - name: Deploy package
        run: pkgdown::deploy_to_branch(new_process = FALSE, run_dont_run = TRUE)
        shell: Rscript {0}
        env: 
          KMP_DUPLICATE_LIB_OK: true
